### ISSUE TITLE
Auto updater doesn't delete old CMILib jars

### ISSUE THREAD

**Issue by Tiippex** [Zrips/CMILib#1]
The auto-updater update with the automatic file removal doesn't seem to work for me:
[16:05:19] [Server thread/ERROR]: Ambiguous plugin name `CMILib' for files `plugins/CMILib1.0.3.5.jar' and `plugins/CMILib1.0.3.6.jar' in `plugins'

I'm running a Paper 1.17.1 server on a Debian KVM virtualized server.
![image](https://user-images.githubusercontent.com/16509128/130649009-efe4482d-45e8-4739-845f-78773ebb6821.png)

The file permissions and the group looks alright.
AutoFileRemoval is set to true

I don't have any errors in the logs:
![image](https://user-images.githubusercontent.com/16509128/130649240-fa9da71d-c1a2-43e1-b3b9-f8c5e999893f.png)

Thanks for your help.
Have a nice day!
Tiippex

**Comment by Zrips** [comment]
@Tiippex 
Some server hosts doesn't give permissions for plugins to perform file removal which can cause this issue with old plugin file remaining after an attempt to remove it. If that happens you might need to either adjust file permissions, which can be more tricky and more complicated or just disable auto updater disabled and update CMILib on somewhat regular basis manually. 
At this moment in time I have no solution.

**Comment by Tiippex** [comment]
@Zrips I have my own dedicated server. The file belongs to the user which runs the server. File permission looks alright as well.

Can you add an error message why the delete step fails? Otherwise, It's quite hard to debug this at our end.
Thanks

**Comment by LangZongz** [comment]
Why not use the `update` folder when it‘s paper？
https://docs.papermc.io/paper/updating#step-2-update-plugins

**Comment by LangZongz** [comment]
Why not use the `update` folder when it‘s paper？
https://docs.papermc.io/paper/updating#step-2-update-plugins
