### ISSUE TITLE
Translation for Night skipping title doesnt work

### ISSUE THREAD

**Issue by 1ntent1on** [Zrips/CMILib#13]
Hello, there seems to be a problem with  sunSpeedingTitle, skippingNight and sunSpeedingSubTitle translation. Basically it will always use the default one, no matter how i change it (adding words, changing colors etc). Tried translating it in all lang files at once, didnt help.
It doesnt matter if i do plugin reload or restart server, it will always stay in its default translation.

Reproduce:
1) Put CMI and CMIL on server
2) In CMIL lang file change sunSpeedingTitle, skippingNight and sunSpeedingSubTitle to smt else, for example:
  sunSpeedingTitle: '&c[hour]'
  skippingNight: '!title!&cTest'
  sunSpeedingSubTitle: '&c[count]&7/&c[total] &7(&c[speed]X&7)'
 3)  Restart server/reload plugin
 4) Set time to night and try to sleep
 5) Take a look at the default title
 
 Versions: 
15:09:41[INFO] CMI: 9.3.0.2 SqLite
15:09:41[INFO] CMILib: 1.2.4.1
15:09:41[INFO] Server: Paper(365) 1.19.3-R0.1-SNAPSHOT
15:09:41[INFO] CMI economy: Enabled Vault: 1.7.3-b131(CMIEInjector) CMI Chat: Disabled
15:09:41[INFO] Modules -> 56 enabled 1 disabled: votifier
15:09:41[INFO] --------------------------------------------------

**Comment by Zrips** [comment]
Sorry about this, will remove those locale lines from CMILib, those should only exist in CMI itself as those are specific ones for this plugin and not general ones. Just modify locale lines in CMI locale files and it should properly pick it up and use those.
