### ISSUE TITLE
Portal Particles Break in CMILib 1.4.0.0 

### ISSUE THREAD

**Issue by mercurialmusic** [Zrips/CMILib#27]
Sorry I initially posted this in the wrong place, but perhaps you prefer it all in one spot there? https://github.com/Zrips/CMI/issues/7957

Particles on existing and new portals have all broken/stopped generating upon update to CMILib 1.4.0.0. Turning them off and on again, both the portal and particle controls, has no effect, restart has no effect. I have not been able to get an error out of it - everything looks normal otherwise, both during startup and normal run. Haven't noticed anything else going weird yet at least.

```
CMI plugin version: 9.6.1.1 BungeeCord CMIB SqLite
CMILib: 1.4.0.0 
Server: Paper(72) 1.20.1-R0.1-SNAPSHOT
CMI economy: Enabled Vault: 1.7.3-b CMI Chat: Disabled 
Modules -> 56 enabled 2 disabled: ranks, skin
```

**Comment by Zrips** [comment]
Resolved
