### ISSUE TITLE
CMILib vs Slimefun BUG

### ISSUE THREAD

**Issue by SrMonsterYT** [Zrips/CMILib#35]
server version: git-Pufferfish-27 (MC: 1.20.1)
CMILib 1.4.4.0
Slimefun: Slimefun vDEV - 1104 (git c977454e)

image: https://prnt.sc/1GmSFjyV42ub

CMILib 1.4.3.5  ( this downward version is working normally )

**Comment by Zrips** [comment]
Should be resolved
