### ISSUE TITLE
Player Skulls reverting custom names

### ISSUE THREAD

**Issue by HorusApl** [Zrips/CMILib#36]
Using any plugin that allows a /skull to get any random player's head with their skin, if you then rename it using any means at all and then drop the item, it will revert back to "Head of <Player_Name>" instead of whatever you named it.

Steps to reproduce:
1. Download CMILib (Jobs or CMI not needed, it's the Lib that does it)
2. Get any skull plugin, I use EssentialsX as it's the most consistent
3. Do /skull <yourname>
4. Rename it using EssentialsX rename command, or a vanilla anvil
5. Drop the skull and pick it up, and the custom name is gone.

**Comment by Zrips** [comment]
Should be resolved
