### ISSUE TITLE
CMILib are not deleted 

### ISSUE THREAD

**Issue by 100petr** [Zrips/CMILib#40]
Old cmilib files are not deleted. The problem has persisted for at least 2.5 years
https://github.com/Zrips/CMI/issues/5881
Will this ever be resolved? Because it's annoying to delete old cmilib files.
And yet it has already been reported here several times..
https://github.com/Zrips/CMILib/issues/1
https://github.com/Zrips/CMILib/issues/30

**Comment by Zrips** [comment]
106b31c6a571d69fe3f12ba067749b712bab0d7d
