### ISSUE TITLE
CMILib not working on Paper 1.21.3

### ISSUE THREAD

**Issue by Relaxing9** [Zrips/CMILib#65]
CMILib Version: 1.5.2.1
Paper Version: 1.21.3 Build Number 10

Error: https://mclo.gs/0MIDWSQ#L300

**Comment by D3dWiz** [comment]
I am also having this issue on latest Purpur version 1.21.3

**Comment by Relaxing9** [comment]
Fixed in CMILib version: 1.5.2.2
