### ISSUE TITLE
I have a better Polish translation for CMILib

### ISSUE THREAD

**Issue by UwU-MrSweetAnanasek-MrXLimitowany-UwU** [Zrips/CMILib#9]
[Locale_PL.txt](https://github.com/Zrips/CMILib/files/9432581/Locale_PL.txt)

**Comment by UwU-MrSweetAnanasek-MrXLimitowany-UwU** [comment]
This translation is much better than what is currently in CMILib

In a few days I am also going to give a better translation to the CMI

**Comment by Zrips** [comment]
Updated. Thanks for contribution.
